name: Bug Report
description: Report a bug in one of the SDKs
labels: ["bug"]
body:
  - type: dropdown
    id: sdk
    attributes:
      label: SDK
      description: Which SDK are you using?
      options:
        - TypeScript/JavaScript
        - Python
        - Go
        - Java
        - C#
        - Ruby
        - Rust
        - Swift
        - PHP
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SDK Version
      description: What version of the SDK are you using?
      placeholder: "0.1.0-beta.2"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue
      placeholder: |
        1. Initialize client with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Runtime version, OS, etc.
      placeholder: |
        - Runtime: Node 22 / Python 3.12 / etc.
        - OS: macOS 14 / Ubuntu 22.04 / Windows 11
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Any relevant error messages or stack traces
      render: shell
    validations:
      required: false
