# frozen_string_literal: true

source "https://rubygems.org"

# Specify gem dependencies in renamed.gemspec
gemspec

group :development, :test do
  gem "bundler", "~> 2.0"
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
  gem "rubocop", "~> 1.0"
  gem "webmock", "~> 3.0"
  gem "yard", "~> 0.9"
end
